### ISSUE TITLE
BUG: No cancel option on Quit

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#100]
If you close the main pane, the app attempts to Quit and presents the following dialog:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/134083189-9fbd6cc4-12d1-4688-b333-32c75efb76b9.png">

However, there is no option to cancel if you don't want to leave running NOR want to quit the app. Maybe you just wanted the window to get out of your way. Related to #99

**Comment by shannona** [comment]
There is now a cancel option
