### ISSUE TITLE
CRITICAL BUG: After Quit and Re-Open, no main pane

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#102]
Somehow in my playing around in last few issues, after quitting Gordian Server, when I re-open it the main pane is absent. The app shows up in my command-tab apps list, and if I select it I can see the menu bar choices for it, but the main pane is missing.

After further investigation, the app had not fully quit. I had to force-quit it to get it such that re-opening open the main pane. Not quite sure how to reproduce, but this is directly related to #99, #100 & #101.

It could also be that if the app is already open, and the app detects that it was opened by a finder open, that it open the main pane if it was closed.

**Comment by Fonta1n3** [comment]
#105 should fix this issue

**Comment by shannona** [comment]
Reported as fixed, closing unless someone replicates it at some point.
