### ISSUE TITLE
BUG: Tries to verify core during/after sleep 

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#104]
I keep getting this dialog error when I leave Gordian Server on, when I return to my Mac, even though I did not click on the Verify button (or even have the app in the foreground). As I was not plugged in, it is probably sleep related.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/134098777-8fe5121c-aaff-477c-8800-4f132abb83e0.png">

**Comment by Fonta1n3** [comment]
Thats not to do with the verify button. It automatically checks for updates in the background, if you do not have an internet connection you will see this error. When your Mac is asleep GS won't be able to fetch updates.

**Comment by ChristopherA** [comment]
Pull it out for now. We maybe later want to suggest to people to use auth, but not this way.

**Comment by Fonta1n3** [comment]
#105 fixes this issue (or at least it should)

**Comment by shannona** [comment]
closing as this should be resolved.
