### ISSUE TITLE
BUG: Tor Error on Setup

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianServer-macOS#106]
Setup generated the error:
```
There was an issue fetching your nodes hidden service address. Your node may not be remotely reachable.
```
I was later able to connect with Gordian Wallet, so it's possible this is just an overly cautious error message, but if so it'll be alarming to users.

Possible cause may be existing installation of Tor from previous installs of Gordian Server. I did *not* get the same error when I did a KILL ALL then reinstall.

This is based on #105 on a Mac Mini running Big Sur (11.5.2).

**Comment by shannona** [comment]
This replicated even after what should have been a totally clean startup, including removing .torrc and Library/Caches/tor.

**Comment by Fonta1n3** [comment]
Did you also remove the /Users/You/Library/Application Support/Bitcoin directory?

**Comment by shannona** [comment]
Yes.

**Comment by shannona** [comment]
What I didn't delete was a .tor directory, which contained files from an install in June 2020. Dunno if that is what caused the problems, but I didn't see it afterward.

**Comment by shannona** [comment]
I can no longer see this (though I've done a number of intensive cleanups as noted). However, @Fonta1n3 has also improved the cleanup of the app, so I'm going to close this unless it recurs.
