### ISSUE TITLE
UX: Install Popup Doesn't Dismiss

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianServer-macOS#107]
The "Install Bitcoin Core v22.0?" popup doesn't dismiss after installation occurs. It should, else users will just keep hitting "Install" again and again (as I did until I decided it was genuinely installed).

Based on #105.

**Comment by shannona** [comment]
Still the case on a fresh install, and I even managed to end up with multiple copies of that "Install" popup.

**Comment by Fonta1n3** [comment]
This should be fixed by https://github.com/BlockchainCommons/GordianServer-macOS/pull/105/commits/0af16c8e46fe8b0dd0b02f808ca79b22fc08ca8c

**Comment by shannona** [comment]
Verified, thanks.
