### ISSUE TITLE
UX: Failed Startup of Network Dies Silently

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianServer-macOS#112]
When a network fails to "Start", such as with a non-responding bitcoind per #109, it dies silently with no messages at all for the user, other than the "Start" button becoming accessible again.

**Comment by Fonta1n3** [comment]
Could you try and replicate this and share what the Xcode console outputs please? It may well have been fixed with my latest commits, I am not able to reproduce.

**Comment by shannona** [comment]
I closed #109 because it looks fixed in the newest commits.

So, that makes the problem unlikely to replicate in real usage (which is how I hit it last week).

I can create new problems if I purposefully break Bitcoin (which is a less likely, but possible situation), but I'll flag that separately as it's not the same error condition.
