### ISSUE TITLE
BUG: On startup failed saving settings file

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#119]
With 1.0.0 #105

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/134788373-e91ec066-fec1-4949-b094-6feaa9930b9b.png">

**Comment by ChristopherA** [comment]
After saying OK, I get:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134788395-6ad831d3-d6ed-4845-b793-b56f2e68a61e.png">

**Comment by Fonta1n3** [comment]
This is something to do with bitcoin core not getting shut down properly or something (which is prevented now). It should be very rare... It may be fixed, I am unable to replicate.

**Comment by shannona** [comment]
Closing this unless it can be replicated.
