### ISSUE TITLE
BUG: On startup Can't fetch nodes hidden service address

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#120]
Started 1.0.0 #105, and I get:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/134788352-e80e779e-d576-4bb2-8a03-8fc16efab65d.png">

**Comment by ChristopherA** [comment]
After saying OK, I then get issue #119, when then leads to 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134788412-72451a5d-cb21-47e9-b71e-5999eb8cca17.png">

**Comment by shannona** [comment]
I'd also reported this as #106. We believe it was related to insufficient cleanup of old data, and that's now resolved, so closing unless we get a repeat.
