### ISSUE TITLE
BUG: Size 0 GB

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#122]
My pruned node is at 100%, but size says 0 GB

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134794693-a7a3626c-5198-4c5f-b0f1-e7c445b62c28.png">

**Comment by shannona** [comment]
Also see #130.

**Comment by shannona** [comment]
And #128.

**Comment by shannona** [comment]
Closing this because it's just a special case of #128.
