### ISSUE TITLE
UX: Order of Node Status

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#123]
I'd like to see the items associated with this specific node at the top, and those with the network as a whole nearer the bottom.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134794714-ad694417-680b-427b-b7ff-22fedf0c52bd.png">

I open, but I think the right order might be:

* Uptime
* Synced
* Blocks (or if pruned: {pruned parameter} of XX Blocks)
* Size XXX GB + Free Space XX GB (ideally one line)
* Pruned /Full/Full-txindex
* Peers In/Out (ideally one line)
* local Mempool / total UTXOs
* Fee rate
* Hashrate
* Difficulty

I might also argue the last two shouldn't be on this panel, but some other UX later.

**Comment by ChristopherA** [comment]
Hmm, probably should mark visibly that you have "private" on.

**Comment by ChristopherA** [comment]
At minimum for release 1.0.0 the ordering needs to be address, even if new options are not integrated.

**Comment by Fonta1n3** [comment]
Can reorder but the other requests are time consuming and will likely not be approved on first iteration as it requires a rework of the UI. I'll change the order now though 👍🏻

**Comment by Fonta1n3** [comment]
Fee rate doesn't make sense as their is no user specified fee rate specified in GS. This requires more work to add as we need to add UI to prompt user to tell us what their target is.

**Comment by shannona** [comment]
Order has been rearranged.
