### ISSUE TITLE
UX: Tor Stats?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#124]
The area under Tor is rather empty. Any bitcoin Tor related stats available?

**Comment by ChristopherA** [comment]
At least the onion address.

**Comment by ChristopherA** [comment]
These are what Gordian Wallet showed:

![image](https://user-images.githubusercontent.com/69103/134823707-f7079970-2e93-43f0-945a-d8794f0524cf.png)

I could see from that the onion address, the name used in QC, and the tor version should at least displayed. If private mode is on should be displayed. Maybe the number of authorized users? Is there any way to tell if an authorized user is connected?

**Comment by Fonta1n3** [comment]
Saying "private mode" is enabled on the tor window doesn't make sense to me, what is it that is private? It would make sense to add it to the bitcoin window as that is the network in question, however it is quite crowded already. There is no way that I know of to tell who is connected to you, from Bitcoin Core it is just 127.0.0.1:<random port> which you can see making rpc commands.

**Comment by shannona** [comment]
There's now new data, but also see #138.
