### ISSUE TITLE
BUG: Display of "Size:" incorrect

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#128]
As of latest #105  29bf6fcb36200bfd877bf787f793e8d5a999a643 on 2021-09-28:

On launch it initially said 1 GB. Now it says 0. It should be space used / space remaining.

If we can't fix this for this release 1.0.0, delete this status line. 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/135158348-ec5a6459-751a-4b1c-8c24-5148788f1941.png">

**Comment by shannona** [comment]
Also see #122 & #130.

**Comment by shannona** [comment]
I flagged this one as "do next" because it includes Christopher's comment that we should either resolve these inaccuracies or else remove the data for 1.0.0, but it refers equally to all three of the linked issues with the data.

**Comment by Fonta1n3** [comment]
@shannona @ChristopherA this value is fetched from `bitcoin-cli getblockchaininfo` `size_on_disk`. Could you please open a terminal, and run `$ Users/you/.gordian/BitcoinCore/bitcoin-22.0/bin/bitcoin-cli getblockchaininfo` and share the output here? Along with the value that is showing in size status on GS UI.

**Comment by shannona** [comment]
```
  "size_on_disk": 960152061,
```

```
Size: 0gb
```

**Comment by shannona** [comment]
Replaced with #143.
