### ISSUE TITLE
BUG: Empty Tor status values

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#129]
As of latest #105  29bf6fcb36200bfd877bf787f793e8d5a999a643 on 2021-09-28:

The Tor status values are blank. These need to be filled/fixed or deleted for release 1.0.0.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/135158872-376d996f-6b1b-4322-8f17-28d88c9bfb2f.png">

**Comment by shannona** [comment]
I refiled this as #138 which maybe has a bit more ideas for replication, but your also seeing it says that it's not just a one-off bug.
