### ISSUE TITLE
BUG: Data Under Tor Went Blank

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianServer-macOS#138]
I'm unfortunately not sure what the circumstances where, but the data under Tor all went blank. It was around when I was testing out client auth codes and QuickConnect codes. Nothing in the Tor log.

The P2P Host, RPC host, etc. The labels were all still there, but nothing showed under them. 

It's not immediately replicable, but perhaps investigation might occur on when these wouldn't update.

I eventually had to stop and start Tor to get them back.

**Comment by shannona** [comment]
Chris also saw this as #129, so it's not a one-off.

**Comment by Fonta1n3** [comment]
@ChristopherA @shannona That would indicate your hidden services configured were not configured/created. Can you open menu item `Tor > Hidden Service Directory` and see if it opens at path: `/Users/you/.gordian/tor/host/bitcoin/rpc/main`?

If nothing exists there then you ought to:
1. quit GS
2. Delete `~/.torrc`
3. Delete `~/.gordian/.tor`
4. Delete `~/.gordian/tor`

**Comment by shannona** [comment]
Hopefully fixed with @90aac0b. Will repoen if it recurs.
