### ISSUE TITLE
NON-CRITICAL BUG: Testnet QuickConnect Fails with Fully Noded

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianServer-macOS#144]
I tested QuickConnect with Testnet and Mainnet on both Fully Noded and Gordian Wallet. The one failure was for Testnet on Fully Noded, which spun for a while:

![59E9C802-E482-437B-ADF7-FCAAFEB6568F](https://user-images.githubusercontent.com/1110886/135351792-34d17903-91ec-4062-9491-f90dba70d015.png)

And eventually failed:

![52D73A64-A769-404A-80F7-873E985CF98A](https://user-images.githubusercontent.com/1110886/135351814-78099d3e-a40a-4d7d-8a0d-76b3c6ac812d.png)

This was consistently replicable.

**Comment by Fonta1n3** [comment]
Not able to reproduce, Tor can get stuck, it definitely happens and is a Tor issue. Best bet to resolve this is to restart tor on the server and force quit and reopen FN to reboot tor on the client.

**Comment by shannona** [comment]
It was very consistent on the previous version, but seems to work following the #147 update, so closing for the moment.
