### ISSUE TITLE
BUG: many many modal errors

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#145]
From current master banch (commit 6e166fcd89810f11c86643594cbc504f4aeb51e7):

Returned from overnight computer sleep and got many*many of these modal errors. So far I've not gotten through all of them.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/135518038-34652c64-438f-4062-addf-19d35ad92cdc.png">

A) There never should be more than 1 of the same error.

B) Do we have to have these errors as modal errors (there are different errors sometimes) when computer wakes?

**Comment by Fonta1n3** [comment]
Yea it should not do that.I had forgotten to set the `autoRefreshTimer` to nil when the app becomes inactive.

https://github.com/Fonta1n3/GordianServer-macOS/commit/311fc8736cd1281559ef17124ac26a4b231aaf1b should fix it.

**Comment by shannona** [comment]
Flagged as fixed in #147, was able to put my Mac Mini to sleep for several minutes without incident.
