### ISSUE TITLE
Duplicated docs

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/GordianServer-macOS#35]
To mirror FN2 repo and Standup scripts we ought to remove the duplicated docs from the root of the repo. 

[CLA.md](https://github.com/BlockchainCommons/Bitcoin-Standup-MacOS/blob/master/CLA.md) and [CONTRIBUTING.md](https://github.com/BlockchainCommons/Bitcoin-Standup-MacOS/blob/master/CONTRIBUTING.md) are both duplicated and also present in [./Docs](https://github.com/BlockchainCommons/Bitcoin-Standup-MacOS/tree/master/Docs).

I put them in docs as I feel it is nice to have a clean root and keep all docs in docs, this also mirrors the other repos I have worked on.

One way or another we ought to adopt a standard and keep it that way across all repos.

**Comment by ChristopherA** [comment]
A number of files have to be special places for GitHub to do the right thing. 

See https://github.com/kmindi/special-files-in-repository-root/blob/master/README.md

I believe that there are even more tricks like these out there.

I've been trying to keep /secure-template up-to-date with current conventions.

There is another trick, which is to put files into a repo named .github which will add that file to all the repos that don't have that file. However, there are some repos that I don't want to have a Contributing.md there at all, so I decided against a universal contributing.md

-- Christopher Allen
