### ISSUE TITLE
When set data dir to external drive, internal drive still used for everything but bitcoin.conf

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [BlockchainCommons/GordianServer-macOS#62]
macOS Catalina 10.15.6. Tested on Fonta1n3's GordianServer-macOS-v0.1.4.dmg, as link to .dmg this repo is dead. 

Problem: 
- In settings, when set data directory to external drive and then starting to download, only bitcoin.conf will be placed in the external drive, while everything else will remain in the internal drive. 

Expected behavior from ~user: 
- Given there's only one data directory setting (not both datadir + blocksdir), one'd expect *everything* would go in this data dir. 

Steps to replicate: 
- Set data dir to external drive. Start it, see bitcoin.conf only file placed in external drive, everything else gets dl'd to internal drive.

**Comment by Fonta1n3** [comment]
Thanks for the issue! Indeed we need to specify a `blocksdir` not just a `datadir`, will let you know when there is an update.

**Comment by Fonta1n3** [comment]
this should be closed
