### ISSUE TITLE
Ability to choose alternative location before Standup

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#71]
There should be an option (maybe a button?) in or before "Ready to Standup" to allow for putting the bitcoin folder someplace other than the default location. My Mac mini has a small internal drive, so I have to use an external drive for bitcoin.

**Comment by Fonta1n3** [comment]
You can, just click the settings button and specify a custom `datadir` then when GS does is checks and installations it will reference that custom`datadir` location.

What is missing is ability to select a custom `blocksdir`.

**Comment by ChristopherA** [comment]
The problem is that this preferences is not an easy choice on a fresh install — you popup windows first. Thus ability to set it needs to be in those first popups.

Preferences was disabled when I tried it before standup (which may have been anither bug).

**Comment by artk47** [comment]
Also, it doesn't actually works afterwords. As if `datadir` changed  ***after*** you `Ready to standup` pressed once - it doesn't work/move data, even if you delete and try from fresh, it ignores the `datadir` and goes ~/Library/Application Support/Bitcoin

You can see that on capture (repeat the first seconds of video):
- GS started and ~/L/AS/Bitcoin folder created, though `datadir` in settings shows other path.

https://user-images.githubusercontent.com/8707649/130325848-3202c145-068a-4f40-9939-b3776a25ec61.mov

**Comment by artk47** [comment]
Also heavily vote for `blocksdir`

**Comment by Fonta1n3** [comment]
this should be closed, only the default matador is supported. you may now specify a custom blocksdir.

**Comment by shannona** [comment]
Options now available on startup.
