### ISSUE TITLE
BUG: Start/Stop Button disabled after error

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#86]
Non-critical bug:

When you click on the "Start" too soon after startup, Bitcoin Core is not ready and you get an error -28 dialogue.

This is not about that error. This is the bug that you get into after that error:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134074827-1dfaa444-8545-45b0-b616-e5d3e2b3e21b.png">

Note that the "Start" button is disabled, but it also hasn't changed to "Stop". So you are stuck. 

Fortunately, you can either click on the "Refresh" icon, or you can "Quit Gordian Server and restart it and it will now work. However, neither is optimal. It should autorefresh (it doesn't seem to currently) and the disabled button could be changed to "Wait. Trying again in X…" so some other solution.

**Comment by shannona** [comment]
It looks like this particular stuck condition is resolved, but there is still a (different) error if you hit start too quickly. I'll flag it as a new Issue.
