### ISSUE TITLE
UX: Is the Add Token "do not ask again" button needed & correct?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#89]
There is a button "do not ask again" that may now be redundant (not sure). In any case, users may be confused.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/69103/134077269-c2580985-c63b-470b-a1bb-816617197f1b.png">

**Comment by Fonta1n3** [comment]
it is not needed, unless you want to automatically alert the user from time to time?

**Comment by shannona** [comment]
It's now removed, witht he options instead being "cancel" and "add"
