### ISSUE TITLE
UX: Move "Refresh" to settings

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#90]
I think this is a dangerous place for "refresh your hidden service", especially as people may not understand their other remote wallets, aunt or uncle they're sharing the node with have to update.

Instead it should be added to Settings near items like kill switches.

![image](https://user-images.githubusercontent.com/69103/134078254-13c3e926-e36c-4f7d-95b2-acce46ae156a.png)

**Comment by shannona** [comment]
The only option on this page is now "Copy".
