### ISSUE TITLE
UX: QuickConnect 1.0 to Clipboard

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#91]
a) It should be clear that this is Quick Connect 1.0, as we'll be hopefully soon adding a QC 2.0.

b) There should be a copy to clipboard option.

![image](https://user-images.githubusercontent.com/69103/134078630-fd8b2ea0-a7a0-4106-8924-61cf3986dc5c.png)

**Comment by shannona** [comment]
This is now labeled 1.0 and there is now a "Copy" button.
