### ISSUE TITLE
UX: Status below buttons

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#95]
I'd like to see the start/stop verify buttons below the network popup list, and have the status info after.

This likely means similarly that the Tor start/stop should be repositioned, putting the Auth Tokens list below that, and then any Tor status items in a single column of bubbles like Gordian Wallet does at bottom.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/69103/134080412-79f5e157-2237-4ce2-853c-869449173028.png">

**Comment by shannona** [comment]
As of last week's 1.0.0 they're right under the network.
