### ISSUE TITLE
BUG: Avoid error code -28

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#96]
This error dialogue happens 100% of the time when starting Gordian Server after stopping it completely. 

a) maybe wait longer before testing the first time.

b) if this is always -28, then maybe not call it out unless it is another error, or it takes MUCH longer.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/69103/134082278-3737cda3-4c85-4717-bc2b-ea30300c102e.png">

**Comment by shannona** [comment]
Resolved in 1.0.0.
